#define ONBOARD_LED PC13
#define NEOPIXEL_PIN PA0
#define KEYBOARD_DAT PA1
#define KEYBOARD_CLK PA2
#define CFG_NSTATUS PA3
#define CFG_NCONFIG PB12
#define CFG_DCLK PB13
#define CFG_DONE PB14
#define SD_SS PA4
#define SD_SCK PA5
#define SD_MISO PA6
#define SD_MOSI PA7
#define SD_DET PA8
#define BUTTON_L PB0
#define BUTTON_R PB1
#define BUTTON_U PB0
#define BUTTON_D PB11
#define PWR_DET PA9
#define MDB0_RX PB6
#define MDB1_TX PB7
#define MDB2 PA10
#define MDB3 PA15
#define MDB4_CFG_DATA PB15
#define MDB5 PB3
#define MDB6 PB4
#define MDB7 PB5
#define OLED_SCL PB8
#define OLED_SDA PB9
